version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: netology_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - netology_net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: netology_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - netology_net

networks:
  netology_net:
    driver: bridge
