version: "3.9"

services:
  backend:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile-backend
    container_name: netology_backend
    ports:
      - "8000:8000"
    env_file:
      - ../../backend/.env  # loads database credentials into the container
    networks:
      - netology_net

  frontend:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile-frontend
    container_name: netology_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - netology_net

networks:
  netology_net:
    driver: bridge
